### ISSUE TITLE
Edit src/Makefile.am and maybe other makefiles to clean up so-setup.exe

### ISSUE THREAD

**Issue by SoDOOManiac** [Zodomaniac/So-Doom#13]
![image](https://github.com/user-attachments/assets/01232102-7849-43e1-b732-05df39f4b10e)
With the commit https://github.com/SoDOOManiac/So-Doom/commit/e80fb22cae41583309fb1d490c9f087589b78fc4
I got rid from creating `so-server.exe`, now only correctly named `so-doom-server.exe` is built,
but `so-setup.exe` is still generated.
So Doom is Doom-only sourceport, so I only need `so-doom-setup.exe` but not `so-setup.exe`.
@fabiangreffrath, could you please tell me or submit a pull request so that `make` builds
`so-doom.exe`, `so-doom-setup.exe` and `so-doom-server.exe` only?
I managed to clean the project from Heretic, Hexen, Strife and `so-server.exe`, but cannot figure out how to get rid
of `so-setup.exe`.

**Comment by fabiangreffrath** [comment]
It's a bit more complicated, because you'll see here that `so-setup.exe` is created first, and then `so-doom-setup.exe` is created as a copy.

https://github.com/SoDOOManiac/So-Doom/blob/e80fb22cae41583309fb1d490c9f087589b78fc4/src/Makefile.am#L191-L192

I guess you'll have to add the `doom-` part to the `noinst_PROGRAMS` line and its `_SOURCES` and `_LDADD` lines and then get rid of the rule that copies that binary over to `SETUP_BINARIES`.

**Comment by SoDOOManiac** [comment]
Thank you! With some edits in GNUmakefile's in pkg directory this worked.
